version: 2.1
orbs:
  node: circleci/node@4.1.1
  snyk: snyk/snyk@0.0.8

working_directory: ~/project

jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version


  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test

 
  security:
    docker:
      - image: circleci/buildpack-deps:stretch 
    environment:
      IMAGE_NAME: garethr/snyky
    
    steps:
      - attach_workspace:
         at: ~/project
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build image
          command: docker build --progress plain -t $IMAGE_NAME .
          environment:
            DOCKER_BUILDKIT: 1
      - run: 
          name: clear report
          command: rm -f ~/project/snyk-report.sarif 
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
          monitor-on-build: false
          fail-on-issues: false
          
          severity-threshold: low
          
          additional-arguments: --sarif --sarif-file-output=~/project/snyk-report
          target-file: Dockerfile

      - store_artifacts:
          path: ~/project/snyk-report.sarif
          destination: artifact-file

            
workflows:
  version: 2
  build:
    jobs:
      - install-node-example
      - test
      - security