version: 2.1
orbs:
  
  snyk: snyk/snyk@0.0.8
jobs:
  
  security:
    docker:
      - image: circleci/buildpack-deps:stretch 
    environment:
      IMAGE_NAME: garethr/snyky
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      
      
      
      - run:
          name: install dependencies
          command: install-npm
            
      - run:
          name: Build image
          command: docker build --progress plain -t $IMAGE_NAME .
          environment:
            DOCKER_BUILDKIT: 1
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
          monitor-on-build: false
          target-file: Dockerfile

workflows:
  version: 2
  build:
    jobs:
      - security